# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-27 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='项目id')),
                ('name', models.CharField(max_length=56, unique=True, verbose_name='项目名')),
                ('status', models.IntegerField(choices=[(1, '等待开始'), (2, '正在运行'), (3, '结束'), (4, '失败')], default=1)),
                ('entry_url', models.URLField(verbose_name='入口链接')),
                ('process_type', models.IntegerField(choices=[(1, 'CSS选择器'), (2, 'CSS'), (3, 'JSON')], default=1, verbose_name='处理类型')),
                ('http_method', models.IntegerField(choices=[(1, 'GET'), (2, 'POST')], default=1, verbose_name='HTTP方法')),
                ('headers', models.TextField(null=True, verbose_name='HTTP Headers')),
                ('cookies', models.TextField(null=True, verbose_name='Cookies')),
                ('valid_domain_model', models.IntegerField(choices=[(1, '当前Hostname匹配'), (2, '泛域名匹配'), (3, '通配')], default=1, verbose_name='合法域名模式')),
                ('valid_path_regex', models.CharField(default='^', max_length=56, null=True, verbose_name='合法Path正则')),
                ('rules', models.TextField(verbose_name='内容提取映射规则')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建于')),
                ('last_indexed', models.DateTimeField(auto_now_add=True, verbose_name='上一次索引')),
            ],
        ),
    ]
