# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-27 15:07
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='rules',
            field=jsonfield.fields.JSONField(verbose_name='内容提取映射规则'),
        ),
    ]
