# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-27 15:09
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20160827_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='payload',
            field=jsonfield.fields.JSONField(default={}, verbose_name='参数'),
        ),
    ]
