# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-27 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_payload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='project',
            name='rules',
        ),
    ]
